baseURL = 'https://datamapu.com/'
languageCode = 'en-us'
title = 'Datamapu'
theme = 'ananke'
uglyURLs = false

[params]
  show_reading_time = true
  socialInHeader = false
  socialInFooter = true

[menu]
[[menu.main]]
  name = "Articles"
  url = "/posts/"
  weight = 3
