baseURL = 'https://datamapu.com/'
languageCode = 'en-us'
title = ''
theme = 'ananke'
uglyURLs = false
googleAnalytics = "G-FJQERFPVYS"
google_tag_manager = "GTM-T6CW23SC"
tags = ["data science", "machine learning", "deep learning", "python", "artificial intelligence"]
features = ["posts", "shortcodes", "related content", "comments"]

[params]
  show_reading_time = true
  socialInHeader = true
  socialInFooter = false
  linkedin = true
  facebook = true
  whatsapp = true
  favicon = "favicon.ico"
  description = 'Data Science and Machine Learning Blog'
  images = ["/static/images/datamapu_logo_schmal.png"]
[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/datamapu"

[menu]
[[menu.main]]
  name = "Articles"
  url = "/posts/"
  weight = 3
[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[taxonomies]
  tag = "tags"
  category = "categories"

