baseURL = 'https://datamapu.com/'
languageCode = 'en-us'
title = ''
theme = 'ananke'
uglyURLs = false
googleAnalytics = ""

[params]
  show_reading_time = true
  socialInHeader = false
  socialInFooter = true
  linkedin = "https://www.linkedin.com/in/frauke-albrecht-90ba511a2/"

[menu]
[[menu.main]]
  name = "Articles"
  url = "/posts/"
  weight = 3
[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[taxonomies]
  tag = "tags"
  category = "categories"

