baseURL = 'https://datamapu.com/'
languageCode = 'en-us'
title = ''
theme = 'ananke'
uglyURLs = false
googleAnalytics = "G-FJQERFPVYS"
google_tag_manager = "GTM-T6CW23SC"

[params]
  show_reading_time = true
  socialInHeader = false
  socialInFooter = true
  twitter = "https://twitter.com/datamapu"
  linkedin = true
  facebook = true	
  favicon = "favicon.ico"

[menu]
[[menu.main]]
  name = "Articles"
  url = "/posts/"
  weight = 3
[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[taxonomies]
  tag = "tags"
  category = "categories"

